import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { SidebarCommon } from "../components/common/SidebarCommon";
import { Provider } from "react-redux";
import { store } from "@/Store/Store";
import ReduxProvider from "@/Store/ReduxProvider";
import SidebarLayout from "@/app/SidebarLayout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {/* <div className="w-screen h-screen">{children}</div> */}
          <SidebarLayout>{children}</SidebarLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
